import cv2
image_color = cv2.imread("girl.bmp",1)
image_gray = cv2.imread("girl.bmp",0)
cv2.imshow("wy210373113color",image_color)
print("获取彩色图像的尺寸：")
print("shape=" , image_color.shape)
print("size=" , image_color.size)
print("dtype=" , image_color.dtype)
cv2.imshow("wy2103273113gray",image_gray)
print("获取灰度图像的尺寸：")
print("shape=" , image_gray.shape)
print("size=" , image_gray.size)
print("dtype=" , image_gray.dtype)
cv2.waitKey()
cv2.destroyAllWindows()
